### ISSUE TITLE
Detect direction of dropdown

### ISSUE THREAD

**Issue by dy** [luwes/selectmenu-polyfill#1]
Any plans to detect direction of dropdown?
Eg. native select shows dropdown the following way at the edge of screen:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/300067/225386827-60c67938-5e8f-49ce-b89c-855d0e1d1920.png">
Would be meaningful to have that for selectmenu, eg.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/300067/225387213-de5d179f-be94-4acd-83a1-d1cf90c6d71a.png">

Now it overflows as:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/300067/225387030-f9587fd9-b779-4017-a1e2-b2bffd83f8fc.png">

There's many possible libs for that:
* [placer](https://github.com/dy/placer)
* [adjust](https://www.npmjs.com/package/adjust)
* [tether](https://github.com/HubSpot/tether)
* [positions](https://github.com/QubitProducts/positions)
* [positionining](https://github.com/mattlewis92/positioning#readme)
* [popper](https://ghub.io/popper)
* [satellite](https://github.com/jkroso/satellite)
* [nanopop](https://github.com/Simonwep/nanopop)
* [floating-ui](https://github.com/atomiks/floating-ui)

**Comment by luwes** [comment]
great feedback, will add support for this eventually.
I'm trying to not add dependencies but shouldn't be too hard to implement I think

**Comment by dy** [comment]
Totally, it must be quite easy to implement simple logic for bottom overflow via getBoundingClientRect
